name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: runteq_graduation_project_test
        ports:
          - 5433:5432

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Add app bin to PATH
        run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            postgresql-client chromium curl libjemalloc2 libvips fonts-liberation

      - name: Database setup
        env:
          RAILS_ENV: test
          PGHOST: db
          DATABASE_URL: postgres://postgres:postgres@db:5432/runteq_graduation_project_test
        run: |
          echo "Waiting for database..."
          for i in {1..20}; do
            if bin/rails db:prepare; then
              echo "Database prepared!"
              break
            else
              echo "Database not ready, retrying in 5s..."
              sleep 5
            fi
          done

      - name: Run Rails tests
        env:
          RAILS_ENV: test
          PGHOST: db
          DATABASE_URL: postgres://postgres:postgres@db:5432/runteq_graduation_project_test
          HEADLESS_CHROME: "true"
        run: bin/rails test:all

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore